### PR TITLE
Fix segfault when D3DCompile is not found

### LINKED ISSUE #32: segfault when D3DCompile could not be found
A null pointer dereference occurs when `D3DCompile` is NULL:
https://github.com/libsdl-org/SDL_gpu_shadercross/blob/62e7df2544abd30005d8eefb5a62d2edede0fe41/src/SDL_gpu_shadercross.c#L556

This happens when `libvkd3d-utils.so.1` could not be loaded.

### PR DESCRIPTION
**Pull request by thatcosmonaut**
Resolves #32

### CODE REVIEW

File: src/SDL_gpu_shadercross.c [hunk 1]
```diff
@@ -560,6 +560,11 @@ static ID3DBlob *SDL_ShaderCross_INTERNAL_CompileDXBC(
     ID3DBlob *errorBlob;
     HRESULT ret;
 
+    if (SDL_D3DCompile == NULL) {
+        SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "%s", "Could not load D3DCompile!");
```
Comment (madebr) [inline src/SDL_gpu_shadercross.c:564]: Looks good to me, but perhaps we should make this library more SDL_mixer/SDL_image-alike?
There, the `IMG_Init` accepts flags that conditionally enables support for certain formats, and returns a mask of all actually enabled formats.
And perhaps this library should also make more use of `SDL_SetError`?

Comment (thatcosmonaut) [reply src/SDL_gpu_shadercross.c:564]: Yeah. There's already a bunch of unused defines in there from when this was a header library and we need to take those out too.

**Comment by flibitijibibo** [comment]
For now let's fix the crash and work on the init and error reporting (#51) separately.
